# macOS-specific settings

# Use platform-native text compositing (CoreAnimation / Metal)
text_composition_strategy platform

# Keyboard
macos_option_as_alt yes
font_size 20.0
map cmd+space send_text all \x00
map opt+cmd+s no_op
