# Tokyo Night color scheme
set -g fish_color_autosuggestion 565f89
set -g fish_color_cancel normal
set -g fish_color_command 7dcfff
set -g fish_color_comment 565f89
set -g fish_color_cwd normal
set -g fish_color_cwd_root red
set -g fish_color_end ff9e64
set -g fish_color_error f7768e
set -g fish_color_escape bb9af7
set -g fish_color_history_current --bold
set -g fish_color_host normal
set -g fish_color_host_remote normal
set -g fish_color_keyword bb9af7
set -g fish_color_normal c0caf5
set -g fish_color_operator 9ece6a
set -g fish_color_option normal
set -g fish_color_param 9d7cd8
set -g fish_color_quote e0af68
set -g fish_color_redirection c0caf5
set -g fish_color_search_match --background=283457
set -g fish_color_selection --background=283457
set -g fish_color_status red
set -g fish_color_user normal
set -g fish_color_valid_path --underline
set -g fish_pager_color_background normal
set -g fish_pager_color_completion c0caf5
set -g fish_pager_color_description 565f89
set -g fish_pager_color_prefix 7dcfff
set -g fish_pager_color_progress 565f89
set -g fish_pager_color_secondary_background normal
set -g fish_pager_color_secondary_completion normal
set -g fish_pager_color_secondary_description normal
set -g fish_pager_color_secondary_prefix normal
set -g fish_pager_color_selected_background --background=283457
set -g fish_pager_color_selected_completion normal
set -g fish_pager_color_selected_description normal
set -g fish_pager_color_selected_prefix normal
