[[session]]
name = "Dotfiles"
path = "~/dotfiles"

[[session]]
name = "Neovim"
path = "~/.config/nvim"

[[session]]
name = "Fish"
path = "~/.config/fish"

[[session]]
name = "Downloads"
path = "~/Downloads"

[[session]]
name = "Foobar2000 Profile"
path = "~/foobar2000/profile"
