#:schema: https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json

[default_session]
preview_command = "lsd -gA --color always --icon always {}"

cache = false

[[session]]
name = "dotfiles"
path = "~/dotfiles"

[[session]]
name = "nvim"
path = "~/.config/nvim"
startup_command = "nvim"

[[session]]
name = "fish"
path = "~/.config/fish"
startup_command = "nvim"

[[session]]
name = "default"
path = "~/"
